export { default as loginPage } from './LoginPage'
export { default as inventoryPage } from './InventoryPage'
export { default as productDetailPage } from './ProductDetailPage'
export { default as cartPage } from './CartPage'
export { default as checkoutPage } from './CheckoutPage'
export { default as header } from './components/HeaderComponent'
